name: Elixir CI

env:
  ELIXIR_VERSION: 1.10.4
  MIX_ENV: test
  OTP_VERSION: 23.0.3
  DATABASE_HOST: postgres

on:
  push
  # push:
  # paths:
  #   - "./patick/**"
jobs:
  test:
    name: Test, format and static analysis
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: patick/deps
          key: patick/deps-${{ env.MIX_ENV }}-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ hashFiles(format('{0}{1}', github.workspace, '/patick/mix.lock')) }}
          restore-keys: |
            patick/deps-${{ env.MIX_ENV }}-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-

      - name: Cache Dialyzer PLTs
        uses: actions/cache@v1
        with:
          path: patick/priv/plts
          key: plts-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ github.sha }}
          restore-keys: |
            plts-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-

      - name: Get Dependencies
        run: cd patick && mix deps.get

      - name: Check Source Code Formatting
        run: cd patick && mix format --check-formatted

      - name: Run Tests
        run: cd patick && mix test --trace

      - name: Run Dialyzer
        run: cd patick && MIX_ENV=dev mix dialyzer
